[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete'
hook_add = '''
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#enable_underbar_completion = 1
  let g:neocomplete#enable_camel_case_completion = 1
  let g:neocomplete#max_list = 10
  let g:neocomplete#sources#syntax#min_keyword_length = 3

  let g:neocomplete#auto_completion_start_length = 2
  let g:neocomplete#enable_auto_close_preview = 0

  let g:neocomplete#max_keyword_width = 10000
'''

# Unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'
  # unite開始時にinsertモードにする
  # ファイル履歴の保存数
  # uniteの起動
  # uniteの終了(起動時と同じコマンドで戻る)
  # esc2回でも戻る
hook_add = '''
  let g:unite_enable_start_insert = 0

  let g:unite_source_file_mru_limit = 50

  noremap <C-p> :Unite -start-insert buffer neomru/file<CR>
  noremap <C-n> :Unite -start-insert file_rec/async file/new directory/new<CR>

  au FileType unite nnoremap <silent> <buffer> <C-n> :q<CR>
  au FileType unite inoremap <silent> <buffer> <C-n> <ESC>:q<CR>
  au FileType unite nnoremap <silent> <buffer> <C-p> :q<CR>
  au FileType unite inoremap <silent> <buffer> <C-p> <ESC>:q<CR>

  au FileType unite nnoremap <silent> <buffer> <ESC><ESC> :q<CR>
  au FileType unite inoremap <silent> <buffer> <ESC><ESC> <ESC>:q<CR>
'''
hook_post_source = '''
  call unite#custom#source("file", "matchers", "matcher_default")
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
  imap <C-k>  <Plug>(neosnippet_expand_or_jump)
  smap <C-k>  <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>  <Plug>(neosnippet_expand_target)

  imap <expr><TAB>
   \ pumvisible() ? "\<C-n>" :
   \ neosnippet#expandable_or_jumpable() ?
   \   "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
        \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif

  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#snippets_directory = '~/.vim/dein/repos/github.com/Shougo/neosnippet-snippets/neosnippets'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# git tools
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'


# file tree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden = 1

  map <C-l> :NERDTreeToggle<CR>
'''

# color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'altercation/solarized'

# left-below mode preview
[[plugins]]
repo = 'itchyny/lightline.vim'


# auto closed
[[plugins]]
repo = 'cohama/lexima.vim'

# ctags support
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
  let g:auto_ctags = 1
  let g:auto_ctags_directory_list = ['.git', '.svn']
  let g:auto_ctags_tags_name = 'tags'
  let g:auto_ctags_filetype_mode = 1
'''
