# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = '''
  let g:go_hightlight_functions = 1
  let g:go_hightlight_methods = 1
  let g:go_hightlight_structs = 1
  let g:go_hightlight_interfaces = 1
  let g:go_hightlight_operators = 1
  let g:go_hightlight_build_constraints = 1

  let g:neocomplete#enable_at_startup = 0
'''

# tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
  let g:vimtex_compiler_latexmk = {
    \ 'background': 1,
    \ 'build_dir': '', 
    \ 'continuous': 1,
    \ 'options': [
    \   '-pdfdvi',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \],
  \}
  let g:vimtex_view_method = "zathura"
  let g:vimtex_view_general_viewer = 'zathura'
  let g:vimtex_view_general_options = '-r @line @pdf @tex'
'''
#smarty template
[[plugins]]
repo = 'vim-scripts/smarty-syntax'
on_ft = ['smarty']

#html
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','smarty']
hook_source ='''
  let g:user_emmet_mode = 'a'
  let g:user_emmet_settings = {
    \'variables' : {
    \  'lang' : 'ja'
    \},
  \}
'''

[[plugins]]
repo = 'vim-scripts/closetag.vim'
on_ft = ['html','smarty']

#markdown preview
#type :MarkdownPreview
[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']
