# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_interfaces = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1

  let g:go_fmt_command = "goimports"
  let g:go_metalinter_autosave = 1
'''

# tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
  let g:vimtex_compiler_latexmk = {
    \ 'background': 1,
    \ 'build_dir': '', 
    \ 'continuous': 1,
    \ 'options': [
    \   '-pdfdvi',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \],
  \}
  let g:vimtex_view_method = "zathura"
  let g:vimtex_view_general_viewer = 'zathura'
  let g:vimtex_view_general_options = '-r @line @pdf @tex'
'''
#smarty template
[[plugins]]
repo = 'vim-scripts/smarty-syntax'
on_ft = ['smarty']

#html
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','smarty']
hook_source ='''
  let g:user_emmet_mode = 'a'
  let g:user_emmet_settings = {
    \'variables' : {
    \  'lang' : 'ja'
    \},
  \}
'''

[[plugins]]
repo = 'vim-scripts/closetag.vim'
on_ft = ['html','smarty']

#markdown preview
#type :MarkdownPreview
[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']

#autolinter
[[plugins]]
repo = 'w0rp/ale'
on_ft = ['ruby','javascript']
hook_source ='''
  let g:ale_linters = {
  \  'javascript': ['eslint','prettier'],
  \  'ruby': ['rubocop'],
  \}
  let g:ale_fixers = {
  \  'javascript' : ['prettier'],
  \}
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 0
  let g:ale_fix_on_save = 1
'''
